particle1:
  op1:
    ratio: 1.0
    index: 1.0
    freq_offset: 0.0
    phase: 0.0
    freq_env:
      attack: 0.005
      decay: 1.5
      sustain: 0.1
      release: 0.8
      mul: 1.0
    amp_env:
      attack: 0.01
      decay: 0.1
      sustain: 0.5
      release: 0.3
      mul: 0.5
    freq_delay: 0.0
    depth_delay: 0.0
    freq_ramp:
      start: 0.0
      end: 0.0
      time: 1.0
    amp_ramp:
      start: 1.0
      end: 0.5
      time: 1.0
  op2:
    ratio: 1.0
    index: 0.800000011920929
    freq_offset: 0.0
    phase: 0.0
    freq_env:
      attack: 0.01
      decay: 0.8
      sustain: 0.4
      release: 0.6
      mul: 1.0
    amp_env:
      attack: 0.01
      decay: 0.1
      sustain: 0.5
      release: 0.3
      mul: 0.5
    freq_delay: 0.0
    depth_delay: 0.0
    freq_ramp:
      start: 0.0
      end: 0.0
      time: 1.0
    amp_ramp:
      start: 1.0
      end: 0.699999988079071
      time: 0.8999999761581421
  op3:
    ratio: 1.0
    index: 0.6000000238418579
    freq_offset: 0.0
    phase: 0.0
    freq_env:
      attack: 0.02
      decay: 1.2
      sustain: 0.3
      release: 0.5
      mul: 1.0
    amp_env:
      attack: 0.01
      decay: 0.1
      sustain: 0.5
      release: 0.3
      mul: 0.5
    freq_delay: 0.0
    depth_delay: 0.0
    freq_ramp:
      start: 0.0
      end: 0.0
      time: 1.0
    amp_ramp:
      start: 1.0
      end: 0.6000000238418579
      time: 1.0
  op4:
    ratio: 1.0
    index: 0.5
    freq_offset: 0.0
    phase: 0.0
    freq_env:
      attack: 0.01
      decay: 0.6
      sustain: 0.5
      release: 0.7
      mul: 1.0
    amp_env:
      attack: 0.01
      decay: 0.1
      sustain: 0.5
      release: 0.3
      mul: 0.5
    freq_delay: 0.0
    depth_delay: 0.0
    freq_ramp:
      start: 0.0
      end: 0.0
      time: 1.0
    amp_ramp:
      start: 1.0
      end: 0.4000000059604645
      time: 0.800000011920929
  op5:
    ratio: 1.0
    index: 0.4000000059604645
    freq_offset: 0.0
    phase: 0.0
    freq_env:
      attack: 0.015
      decay: 1.0
      sustain: 0.2
      release: 0.6
      mul: 1.0
    amp_env:
      attack: 0.01
      decay: 0.1
      sustain: 0.5
      release: 0.3
      mul: 0.5
    freq_delay: 0.0
    depth_delay: 0.0
    freq_ramp:
      start: 0.0
      end: 0.0
      time: 1.0
    amp_ramp:
      start: 1.0
      end: 0.30000001192092896
      time: 1.0
  op6:
    ratio: 0.5
    index: 0.30000001192092896
    freq_offset: 0.0
    phase: 0.0
    freq_env:
      attack: 0.025
      decay: 0.8999999999999999
      sustain: 0.3
      release: 0.8999999999999999
      mul: 1.0
    amp_env:
      attack: 0.01
      decay: 0.1
      sustain: 0.5
      release: 0.3
      mul: 0.5
    freq_delay: 0.0
    depth_delay: 0.0
    freq_ramp:
      start: 0.0
      end: 0.0
      time: 1.0
    amp_ramp:
      start: 1.0
      end: 0.20000000298023224
      time: 1.0
  carrier:
    ratio: 1.0
    index: 0.0
    freq_offset: 0.0
    phase: 0.0
    freq_env:
      attack: 0.01
      decay: 0.1
      sustain: 0.5
      release: 0.3
      mul: 50
    amp_env:
      attack: 0.01
      decay: 0.1
      sustain: 0.8
      release: 0.5
      mul: 0.15
    freq_delay: 0.0
    depth_delay: 0.0
    freq_ramp:
      start: 0.0
      end: 0.0
      time: 1.0
    amp_ramp:
      start: 1.0
      end: 0.800000011920929
      time: 1.0
