[tool:pytest]
testpaths = tests
addopts = 
    --cov=.
    --cov-report=html
    --cov-report=term-missing
    --cov-exclude=tests/*
    --cov-fail-under=90
    -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*